### PR TITLE
8.1 changes

### PR DESCRIPTION
**Pull request by alviteri**

### CODE REVIEW

**Comment by jerpelea** [comment]
https://www.anandtech.com/show/11338/qualcomm-announces-snapdragon-660-630-mobile-platforms

there is no kryo mention on sdm630

**Comment by alviteri** [comment]
screenshot_20180303-081230

**Comment by jerpelea** [comment]
https://en.m.wikipedia.org/wiki/List_of_Qualcomm_Snapdragon_systems-on-chip

**Comment by alviteri** [comment]
screenshot_20180303-085310

**Comment by alviteri** [comment]
Probably some apps are showing wrong info then

**Comment by kholk** [comment]
Please, close this PR.
At least two of 3 commits are wrong.

**Pull request closed without merging**
