### PR TITLE
Remove discard in fstab

### PR DESCRIPTION
**Pull request by luk1337**
Bug: 30807864
Change-Id: If3f67d5b7b15409c2717ef0d92851ca46677e4ff

### CODE REVIEW

**Comment by alviteri** [comment]
Is intentionally the space before noatime ?

**Comment by luk1337** [comment]
oops

**Comment by luk1337** [comment]
fix'd

**Comment by jerpelea** [comment]
please link original commit

**Comment by luk1337** [comment]
https://android.googlesource.com/device/moto/shamu/+/a02879f0e7186f62bd82acad4ba7265403a6991c

**Comment by luk1337** [comment]
tl;dr discard on / doesn't make any sense cause it's read only and discard on /data is done by android every once in a while.

**Comment by jerpelea** [comment]
add it to the commit message in all commits

**Comment by luk1337** [comment]
Done, amended changes in: nile, tone, yoshino, loire.

**Pull request merged**
