### PR TITLE
 Move libnfc-nci.conf and NXP_CHIP_FW_TYPE to nile shared

### PR DESCRIPTION
**Pull request by ix5**
All nile devices share the `PN553` chip and the NCI config can be unified.

This change also moves the files from `/system/etc` to `/vendor/etc` for treble compliance.

### CODE REVIEW

**Comment by alviteri** [comment]
@jerpelea @ix5 commit fdd8ebd8232ef5f6b65bc1e73cce06e5ce40314d is ok but it must be in system and not in vendor partition see commit https://github.com/sonyxperiadev/device-sony-discovery/pull/25

also if you do this and removing device/generic/common from manifest you will cause error in build like

ninja: error: 'device/generic/common/nfc/libnfc-nci.conf', needed by 
                   '/out/target/product/generic/system/etc/libnfc-nci.conf', missing and no known rule to make it

**Comment by jerpelea** [comment]
did you select a product ?
I see that the target is generic ! (/out/target/product/generic/)

**Comment by alviteri** [comment]
this error happens with sdm845 target

**Comment by alviteri** [comment]
@jerpelea see pixel 3 conf
https://android.googlesource.com/device/google/crosshatch/+/refs/tags/android-9.0.0_r46/device.mk#392

**Pull request merged**
