### PR TITLE
nile: update fstab matching device partitions

### PR DESCRIPTION
**Pull request by alviteri**
H4213:/dev/block/platform/soc/c0c4000.sdhci/by-name $ ls
LTALabel  appslog      cmnlib64_a  devcfg_b  dsp_b       hyp_b        mdtp_a        modem_b   persist    rpm_a   storsec   tzxfl_a        vendor_b     xflkeystorebak
Qnovo     bluetooth_a  cmnlib64_b  devinfo   frp         keymaster_a  mdtp_b        modemst1  pmic_a     rpm_b   system_a  tzxfl_b        xbl_a
TA        bluetooth_b  cmnlib_a    diag      fsc         keymaster_b  mdtpsecapp_a  modemst2  pmic_b     sec     system_b  tzxflattest_a  xbl_b
abl_a     boot_a       cmnlib_b    dip       fsg         keystore     mdtpsecapp_b  msadp     rddata     splash  toolsfv   tzxflattest_b  xfl_a
abl_b     boot_b       ddr         dpo       fsmetadata  limits       misc          oem_a     rdimage_a  ssd     tz_a      userdata       xfl_b
apdp      cdt          devcfg_a    dsp_a     hyp_a       logfs        modem_a       oem_b     rdimage_b  sti     tz_b      vendor_a       xflkeystore

Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by alviteri** [comment]
@jerpelea for the following partitions what we should follow

system .... system_a or system_b
oem ........ oem_a or oem_b
boot ........ boot_a or boot_b
dsp ......... dsp_a or dsp_b
modem ... modem_a or modem_b
bluetooth . bluetooth_a or bluetooth_b ......

**Comment by alviteri** [comment]
also see we dont have FOTAKernel partition available now

**Comment by jerpelea** [comment]
on an A/B partition system you use slotselect

**Comment by jerpelea** [comment]
this update will make devices unbootable since mile does not use AVB2

**Comment by jerpelea** [comment]
what is the actual change ?
the diff shows that you changed all lines

**Comment by alviteri** [comment]
second this https://android.googlesource.com/platform/external/avb/+/android-8.1.0_r11/README.md#a_b-support you should enable the flag to make slotselect works

**Comment by kholk** [comment]
This PR makes Discovery unbootable.

**Pull request closed without merging**
